config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  root 'static_pages#home'
  get '/dashboard',                       to: 'users#dashboard',          as: :dashboard
  get '/users/:user_id/reservations/:id', to: 'reservations#show_active', as: :active_reservation

  resources :users, only: [:show, :edit, :update] do
    resources :addresses,    only: [:index, :create, :destroy]
    resources :reservations, only: [:index]

    member do
      get 'activate_teacher'
      get 'projects'
      get 'teacher', to: 'reservations#teacher_index'
    end

    collection do
      get 'apply_teacher'
    end

    resources :comments, only: [:create], module: :users
    resources :notifications, only: [:index]
  end

  resources :projects do
    member do
      get 'detail'
    end

    collection do
      get 'feed'
    end

    resources :reservations, except: [:show] do
      member do
        put 'confirm'
      end
    end

    resources :comments, only: [:create], module: :projects
  end

  get '/projects/:project_id/reservations/:id',
      to: 'reservations#show_passive', as: :passive_reservation

  resources :messages, only: [:create]
  resources :rooms,    only: [:show, :index]

  resource :prefecture, only: [] do
    collection do
      get 'cities'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notificatable, polymorphic: true
  belongs_to :visited, class_name: 'User'
  belongs_to :visitor, class_name: 'User'
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def index
    current_user.passive_notifications.
      where(checked: false).update_all(checked: true)

    @notifications = current_user.
      passive_notifications.preload(:notificatable, :visitor, :visited).
      order(created_at: 'DESC').decorate
  end

  private

  def correct_user
    redirect_to root_path unless current_user == User.find(params[:user_id])
  end
end

app/views/notifications/_feed.html.erb
<div class="list-group pt-5">
  <% @notifications.each do |notification| %>
    <% case notification.notificatable_type
      when 'Reservation' then %>

      <%= link_to passive_reservation_path(notification.notificatable.project, notification.notificatable), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
        <small class='text-right'><%= notification.created_at %> ago</small>
        <p class="mb-1"><%= notification.visitor_name %>があなたのプロジェクト「<%= notification.project_title %>」を予約しました。</p>
      <% end %>

    <% when 'Comment' then %>
      <% if notification.notificatable.commentable_type == 'User' %>
        <%= link_to user_path(notification.visited), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
          <small><%= notification.created_at %> ago</small>
          <p class="mb-1"><%= notification.visitor_name %>があなたに評価をつけました。</p>
        <% end %>
      <% else %>
        <%= link_to detail_project_path(notification.notificatable), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
          <small><%= notification.created_at %> ago</small>
          <p class="mb-1"><%= notification.visitor_name %>があなたのプロジェクト「<%= notification.commentable_project_title %>」に評価をつけました。</p>
        <% end %>
      <% end %>

    <% when 'Room' then %>

      <%= link_to room_path(notification.notificatable), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
        <small><%= notification.created_at %> ago</small>
        <p class="mb-1"><%= notification.visitor_name %>から予約メッセージが届きました。</p>
      <% end %>

    <% end %>
  <% end %>
</div>

app/views/notifications/index.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">
    <h2 class='heading'><span>通知一覧</span></h2>

    <div class='container'>
      <div class='row'>
        <div class='col-11 mx-auto'>
          <%= render 'feed', notifications: @notifications%>
        </div>
      </div>
    </div>
  </div>

</div>