config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  root 'static_pages#home'
  get '/dashboard',                       to: 'users#dashboard',          as: :dashboard
  get '/users/:user_id/reservations/:id', to: 'reservations#show_active', as: :active_reservation

  resources :users, only: [:show, :edit, :update] do
    resources :addresses,    only: [:index, :create, :destroy]
    resources :reservations, only: [:index]

    member do
      get 'activate_teacher'
      get 'projects'
      get 'teacher', to: 'reservations#teacher_index'
    end

    collection do
      get 'apply_teacher'
    end

    resources :comments, only: [:create], module: :users
    resources :notifications, only: [:index]
  end

  resources :projects do
    member do
      get 'detail'
    end

    collection do
      get 'feed'
    end

    resources :reservations, except: [:show] do
      member do
        put 'confirm'
      end
    end

    resources :comments, only: [:create], module: :projects
  end

  get '/projects/:project_id/reservations/:id',
      to: 'reservations#show_passive', as: :passive_reservation

  resources :messages, only: [:create]
  resources :rooms,    only: [:show, :index]

  resource :prefecture, only: [] do
    collection do
      get 'cities'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Calculator
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/.freeze

  scope :teacher_accounts, -> {
    where(teacher: true)
  }

  devise :database_authenticatable,   :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :timeoutable,  :omniauthable

  validates :username, presence: true,
                       uniqueness: { case_sensitive: :false },
                       length: { in: 2..50 }

  validates :phone_number, uniqueness: { case_sensitive: :false },
                           allow_nil: true

  validates :introduction, length: { maximum: 255 },
                           allow_nil: true

  after_validation :check_correct_number

  has_many :projects,  dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :active_reservations,  class_name: 'Reservation',
                                  foreign_key: 'requester_id',
                                  dependent: :destroy

  has_many :passive_reservations, through: :projects,
                                  foreign_key: 'project_id',
                                  source: :reservations,
                                  dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries,  dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :active_comments, class_name: 'Comment',
                             foreign_key: 'commenter_id',
                             dependent: :destroy

  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: 'visited_id',
                                   dependent: :destroy

  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: 'visitor_id',
                                  dependent: :destroy

  has_one :performance, as: :performancable, dependent: :destroy

  def available_addresses
    5 - addresses.count
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      mail = User.dummy_email(auth)
      user = User.new(
        uid: auth.uid,
        provider: auth.provider,
        email: mail,
        username: auth.info.name,
        password: Devise.friendly_token[0, 20],
        # image:  auth.info.image
        unconfirmed_email: mail
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.dummy_email(auth)
    auth.info.email || "#{auth.uid}-#{auth.provider}@example.com"
  end

  def activate_teacher
    update_attribute(:teacher, true)
  end

  def project_owner?(project)
    true if project.user == project.owner
  end

  private

  def check_correct_number
    return if phone_number.blank?
    unless phone_number.match VALID_PHONE_REGEX
      errors.add(:phone_number, 'type correct phone number')
    end
  end

  def get_finished_record
    Reservation.sort_reservations_by_status(self, supplier: true, status: 'finished').size
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < CommentsController
  before_action :set_commentable
  before_action :correct_commenter

  def create
    @comment = @commentable.comments.create(comment_params)
    @comment.commenter = current_user
    if @comment.save
      @comment.create_notification
      redirect_to @commentable, notice: 'Your comment was successfully posted!'
    else
      render 'users/show'
    end
  end

  private

  def correct_commenter
    redirect_to user_path(@commentable) if current_user == @commentable
  end

  def set_commentable
    @commentable = User.find(params[:user_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    dashboard_path
  end

  def after_update_path_for(resource)
    dashboard_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    dashboard_path
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:projects]
  before_action :authenticate_nonteacher, only: [:apply_teacher, :activate_teacher]
  before_action :unconfirmed?, only: :activate_teacher
  before_action :correct_user, only: [:edit, :update]

  def index; end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.includes([:commenter]).decorate
  end

  def dashboard
    @checked_active_reservations = Reservation.sort_reservations_by_status(
      current_user, requester: true, status: 'checked'
    )
  end

  def apply_teacher; end

  def activate_teacher
    user = User.find(params[:id])
    if user == current_user
      ActivateMailer.apply_teacher_account(user).deliver_now
      ActivateTeacherJob.set(wait: 30.seconds).perform_later user
      user.create_performance
      flash[:notice] = 'teacher accountの申請を受け付けました、メールをご確認ください'
      redirect_to root_path, status: 200
    else
      redirect_to root_path
    end
  end

  def projects
    @user = User.find(params[:id])
    @projects = @user.projects.includes(:rich_text_content)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User情報を更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :image, :phone_number, :introduction)
  end

  def authenticate_nonteacher
    redirect_to root_path if current_user.teacher?
  end

  def unconfirmed?
    redirect_to root_path if current_user.unconfirmed_email.present?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_image(user)
    return image_tag(user.image), class: '' if user.image
    gravatar_for(user)
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "ui-w-100 rounded-circl")
  end
end

app/views/users/_show_teacher_account.html.erb
<div class="bg-container">
  <div class="container">
    <div class="text-center py-5">
      <%= user_image(user) %>
      <div class="col-md-8 col-lg-6 col-xl-5 p-0 mx-auto">
        <h4 class="font-weight-bold my-4 text-white"><%=  user.username %></h4>
        <div class="text-muted mb-4">
          <%= user.introduction %>
        </div>
      </div>

      <div class="text-center">
        <div class="d-inline-block text-dark">
          <span class="text-muted"><%= link_to "#{user.projects.size} projects", projects_user_path(user), class: 'text-dark' %></span>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">

</div>

<div class="container pt-5 pb-5 my-page-container">
  <div class="row">
    <div class='col-10 mx-auto'>
       <%= render 'shared/notification' %>
      <% if user.teacher? %>
        <%= render 'shared/performance_bar', record: user.performance&.total_record, rate: user.performance&.average_score %>
        <%= render 'comments/index', comments: @comments %>
        <% if current_user && current_user != user %>
          <%= render 'comments/form',  commentable: user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_show_user.html.erb
<div class="bg-container">
  <div class="container">
    <div class="text-center py-5">
      <%= user_image(user) %>
      <div class="col-md-8 col-lg-6 col-xl-5 p-0 mx-auto">
        <h4 class="font-weight-bold my-4 text-white"><%=  user.username %></h4>
        <div class="text-muted mb-4">
          <%= user.introduction %>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">

</div>

<div class="container pt-5 pb-5 my-page-container">
  <div class="row">
    <div class='col-10 mx-auto'>
      <%= render 'shared/notification' %>
      <% if user.teacher? %>
        <%= render 'shared/performance_bar', record: user.performance&.total_record, rate: user.performance&.average_score %>
        <%= render 'comments/index', commentable: user %>
        <% if current_user && current_user != user %>
          <%= render 'comments/form',  commentable: user %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/apply_teacher.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">
    <%= render 'shared/notification' %>
    <h1 class="display-4">
      あなたのスキルを使って、<br> 困っている人を助けよう！
      <br>
    </h1>
    <p>些細なことで困っている人がたくさんいます</p>
    <% if unconfirmed?(current_user) %>
      <div class="btn-toolbar mb-2 mb-md-0">
        <p>
          <%= link_to "#", style: 'pointer-events: none;' do %>
            <button type="button" class="btn btn-secondary btn-lg mr-3">teacherアカウントの登録にはメール認証が必要です</button>
          <% end %>
        </p>
        <p><%= link_to 'メール認証をする', edit_user_registration_path %></p>
      </div>
    <% else %>
      <div class="btn-toolbar mb-2 mb-md-0">
        <%= link_to activate_teacher_user_path(current_user) do %>
          <button type="button" class="btn btn-info btn-lg mr-3">apply teacher account</button>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/dashboard.html.erb
<%= render 'shared/sidenav' %>

<div class="container dashboard-container">
  <div class="jumbotron">
    <%= render 'shared/notification' %>

    <h2 class='heading'><span>ダッシュボード</span></h2>

    <div class="col-10 mx-auto">
      <% if current_user.decorate.has_unchecked_notifications? %>
        <div class='pt-4'>
          <div class="alert alert-primary" role="alert">
            You got <%= current_user.decorate.unchecked_notifications_count %> notifications. check <%= link_to 'here', user_notifications_path(current_user) %>
          </div>
        </div>
      <% end %>

      <div class="mt-5 checked-projects">
        <h2> 実行予定のProject </h2>
        <% if @checked_active_reservations.present? %>
          <small>日時をお間違えのないようご確認ください</small>
          <%= render 'reservations/active_feed', reservations: @checked_active_reservations %>
        <% else %>
          <p>実行予定のProjectはございません</p>
        <% end %>
      </div>
    </div>
  </div>

<footer>
    Repository maintained by <%= link_to 'Kwanji Choi', 'https://github.com/KwanjiChoi/my_portfolio', target: :_blank %>
</footer>

</div>

app/views/users/edit.html.erb
<%= render 'shared/sidenav' %>

<div class='container'>

  <div class='jumbotron'>

    <h2 class='heading'><span>ユーザー設定</span></h2>

    <div class='row'>

      <div class='edit-form col-9 mx-auto pt-5'>

        <%= form_with model: @user, local: true, class: 'mx-auto' do |f| %>
          <%= render 'shared/error_messages', resource: @user %>

          <div class="form-group">
            <%= f.label :username, 'Username', class: 'control-label' %>
            <div class="controls">
              <%= f.text_field :username, class: 'form-control col-10', placeholder: 'username' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :phone_number, 'Phone number', class: 'control-label' %> <small class='ml-3'>※ No hyphen</small>
            <div class="controls">
              <%= f.text_field :phone_number, class: 'form-control col-5' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :introduction, 'Introduction Text', class: 'control-label' %> <small class='ml-3'>※ Within 255 characters</small>
            <div class="controls">
              <%= f.text_area :introduction, class: 'form-control col-7', rows: 5 %>
              <div class='pt-2'>
                <span class="count"><%= 255 - (@user.introduction&.size).to_i %></span> characters left
              </div>
            </div>
          </div>

          <%= f.submit "Update", class: 'btn btn-primary mt-3' %>

        <% end %>


      </div>

    </div>
  </div>
</div>


<script>
  $(function(){
    var countMax = 255;
    $('textarea').bind('keydown keyup keypress change',function(){
      var thisValueLength = $(this).val().length;
      var countDown = (countMax)-(thisValueLength);
      $('.count').html(countDown);

      if(countDown < 0){
        $('.count').css({color:'#ff0000',fontWeight:'bold'});
      } else {
        $('.count').css({color:'#000000',fontWeight:'normal'});
      }
    });
    $(window).load(function(){
      $('.count').html(countMax);
    });
  });
</script>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/projects.html.erb
<% if current_user %>
  <%= render 'shared/sidenav' %>
<% else %>
  <%= render 'shared/not_sign_in_sidenav' %>
<% end %>


<div class="container">
  <div class="jumbotron">

    <%= render 'shared/notification' %>

    <div class="container">
      <div class="text-center mb-5">
        <h2 class="display-20 display-md-18 display-lg-16"><%= @user.username %>のプロジェクト </h2>
      </div>
      <div class="row">
        <% unless @projects.any? %>
          募集中のプロジェクトはありません
        <% end %>
        <% @projects.each do |project| %>
          <div class="col-lg-6 col-md-6 product-box">
            <article class="card card-style2">
              <div class="card-img">
                <%= image_tag project.main_image.index_thumb.url, class: 'rounded-top' %>
                <div class="date"><span><%= project.created_at.strftime("%d") %></span><%= project.created_at.strftime("%b") %></div>
              </div>
              <div class="card-body">
                <h3 class="h5"><%= link_to "#{project.title}", detail_project_path(project) %></h3>
                <p class="display-30"><%= project.short_content %></p>
              </div>
              <div class="card-footer">
                <ul>
                  <li><a href="#!"><i class="fas fa-user"></i>Vickie</a></li>
                  <li><a href="#!"><i class="far fa-comment-dots"></i><span>11</span></a></li>
                </ul>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<%= render 'shared/sidenav' %>


<% if @user.teacher? %>
  <%= render 'show_teacher_account', user: @user %>
<% else %>
  <%= render 'show_user' , user: @user %>
<% end %>