config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  root 'static_pages#home'
  get '/dashboard',                       to: 'users#dashboard',          as: :dashboard
  get '/users/:user_id/reservations/:id', to: 'reservations#show_active', as: :active_reservation

  resources :users, only: [:show, :edit, :update] do
    resources :addresses,    only: [:index, :create, :destroy]
    resources :reservations, only: [:index]

    member do
      get 'activate_teacher'
      get 'projects'
      get 'teacher', to: 'reservations#teacher_index'
    end

    collection do
      get 'apply_teacher'
    end

    resources :comments, only: [:create], module: :users
    resources :notifications, only: [:index]
  end

  resources :projects do
    member do
      get 'detail'
    end

    collection do
      get 'feed'
    end

    resources :reservations, except: [:show] do
      member do
        put 'confirm'
      end
    end

    resources :comments, only: [:create], module: :projects
  end

  get '/projects/:project_id/reservations/:id',
      to: 'reservations#show_passive', as: :passive_reservation

  resources :messages, only: [:create]
  resources :rooms,    only: [:show, :index]

  resource :prefecture, only: [] do
    collection do
      get 'cities'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class='alert alert-danger'>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_google_map.html.erb
<div id="map"></div>

<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= resource.latitude %>, lng: <%= resource.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: test
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= resource.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>

app/views/shared/_not_sign_in_sidenav.html.erb
<%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>



<nav class="navbar navbar-expand-md navbar-dark fixed-left">
  <%= link_to 'My portforio', root_path, class: 'navbar-brand logo', data: { "turbolinks" => false } %>


  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">プロジェクトを探す</a>
        <div class="dropdown-menu">
          <% category_list.each do |category| %>
            <%= link_to category.name, feed_projects_path(category_id: category.id), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_notification.html.erb
<% if flash.any? %>
  <div id="notifications" class='alert alert-success'>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <% end %> 
  </div>
<% end %>

app/views/shared/_performance_bar.html.erb
<div class="mb-5 row">
  <div class='col-md-6 text-center mt-3'>
    <p>予約実績</p>
    <h4><%= record %>件</h4>
  </div>
  <div class='col-md-6 text-center mt-3'>
    <p class='text-center'>平均評価</p>
    <% if rate.nil? %>
      <div class="stars" style="--rating: 0;"></div>
      <p class='mt-2'>まだ評価はございません</p>
    <% else %>
      <div class="stars" style="--rating: <%= rate %>;"></div>
      <p class='mt-2'><%= rate %>点</p>
    <% end %>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>

<nav class="navbar navbar-expand-md navbar-dark fixed-left">
  <%= link_to 'My portforio', root_path, class: 'navbar-brand logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
          aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'My page', user_path(current_user), class: 'nav-link' %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">プロジェクトを探す</a>
        <div class="dropdown-menu">
          <% category_list.each do |category| %>
            <%= link_to category.name, feed_projects_path(category_id: category.id), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to 'ダッシュボード', dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '予約管理', user_reservations_path(current_user), class: 'nav-link' %>
      </li>


      <% if current_user.teacher? %>
        <li class="nav-item">
          <%= link_to 'MYプロジェクト', projects_path, class: 'nav-link' %>
          <%= link_to 'Teacher', teacher_user_path(current_user), class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to '人に教える', apply_teacher_users_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">account</a>
        <div class="dropdown-menu">
          <%= link_to 'セキュリティ設定', edit_user_registration_path, class: 'dropdown-item' %>
          <%= link_to 'アカウント設定', edit_user_path(current_user), class: 'dropdown-item' %>
          <% if current_user.teacher? %>
            <%= link_to 'ワークスペース登録', user_addresses_path(current_user), class: 'dropdown-item' %>
          <% end %>
          <a class="dropdown-item">支払い方法 <small>※準備中</small></a>
          <%= link_to '通知', user_notifications_path(current_user), class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>