config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  root 'static_pages#home'
  get '/dashboard',                       to: 'users#dashboard',          as: :dashboard
  get '/users/:user_id/reservations/:id', to: 'reservations#show_active', as: :active_reservation

  resources :users, only: [:show, :edit, :update] do
    resources :addresses,    only: [:index, :create, :destroy]
    resources :reservations, only: [:index]

    member do
      get 'activate_teacher'
      get 'projects'
      get 'teacher', to: 'reservations#teacher_index'
    end

    collection do
      get 'apply_teacher'
    end

    resources :comments, only: [:create], module: :users
    resources :notifications, only: [:index]
  end

  resources :projects do
    member do
      get 'detail'
    end

    collection do
      get 'feed'
    end

    resources :reservations, except: [:show] do
      member do
        put 'confirm'
      end
    end

    resources :comments, only: [:create], module: :projects
  end

  get '/projects/:project_id/reservations/:id',
      to: 'reservations#show_passive', as: :passive_reservation

  resources :messages, only: [:create]
  resources :rooms,    only: [:show, :index]

  resource :prefecture, only: [] do
    collection do
      get 'cities'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Calculator
  RECENT_COUNT = 6

  scope :recent_projects, -> {
    order(id: :desc).limit(RECENT_COUNT)
  }

  scope :popular_projects, -> {
    find(Reservation.group(:project_id).
          order('count(project_id) desc').limit(3).
            pluck(:project_id))
  }

  belongs_to :user
  belongs_to :project_category

  has_many :reservations,  dependent: :destroy
  has_many :comments,      as: :commentable,   dependent: :destroy
  has_many :notifications, as: :notificatable, dependent: :destroy

  mount_uploader :main_image, ImageUploader

  validates :main_image,    presence: true
  validates :title,         presence: true, length: { in: 2..50 }
  validates :content,       presence: true, length: { in: 100..2000 }
  validate  :check_phone_reservation

  has_one :location, class_name: 'Project::Location', dependent: :destroy
  has_one :performance, as: :performancable, dependent: :destroy

  accepts_nested_attributes_for :location, allow_destroy: true

  has_rich_text :content

  # https://qiita.com/QUANON/items/ae47ae23c572d498050d
  delegate :strip_tags, to: 'ApplicationController.helpers'
  delegate :username,   to: :user

  alias_method :owner,    :username
  alias_method :supplier, :user

  def category_name
    project_category.name
  end

  def location_name
    "#{location&.prefecture&.name} #{location&.city&.name}"
  end

  def short_content
    # .includes([:rich_text_content])
    strip_tags(content.to_s).gsub(/[\n]/, "").strip[0..75] + '...'
  end

  private

  def check_phone_reservation
    if phone_reservation == true
      errors.add(:phone_reservation, "電話予約を設定するには電話番号の登録が必要です") if user.phone_number.blank?
    end
  end

  def get_finished_record
    reservations.where(status: 'finished').size
  end
end

app/models/project/location.rb
class Project::Location < ApplicationRecord
  belongs_to :prefecture, foreign_key: "prefecture_id"
  belongs_to :city, foreign_key: "city_id"
  belongs_to :project
end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < CommentsController
  before_action :set_commentable
  before_action :correct_commenter

  def create
    @comment = @commentable.comments.create(comment_params)
    @comment.commenter = current_user
    if @comment.save
      @comment.create_notification
      redirect_to detail_project_path(@commentable), notice: 'Your comment was successfully posted!'
    else
      render 'projects/detail'
    end
  end

  private

  def correct_commenter
    redirect_to detail_project_path(@commentable) if current_user == @commentable.user
  end

  def set_commentable
    @commentable = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:detail, :feed]
  before_action :correct_project_supplier, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_teacher_account!, except: [:detail, :feed]
  before_action :set_project, only: [:show, :destroy, :detail, :edit, :update]

  PER = 30

  def index
    @projects = current_user.projects.includes([
      :project_category,
      :rich_text_content,
      location: [:prefecture, :city],
    ]).page(params[:page]).per(PER)
  end

  def new
    @project = Project.new
    @project.build_location
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      @project.create_performance
      redirect_to project_path(@project), notice: 'created successfully'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Projectを更新しました'
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    if project.destroy
      redirect_to projects_path, notice: 'deleted successfully'
    else
      render :show
    end
  end

  def detail
    @comments = @project.comments.includes([:commenter]).decorate
  end

  def feed
    @category = ProjectCategory.find(params[:category_id]) if params[:category_id]
    @prefecture = Prefecture.find_by(name: params[:prefecture]) if params[:prefecture]
    if @category
      @projects = Project.where(
        "project_category_id = ?", @category.id
      ).includes([
        :project_category,
        :rich_text_content,
        :user,
        location: [:prefecture, :city],
      ]).page(params[:page]).per(PER)
    else
      if @prefecture
        @projects = Project.joins(:location).where(
          'prefecture_id = ?', @prefecture.id
        ).includes([
          :project_category,
          :rich_text_content,
          :user,
          location: [:prefecture, :city],
        ]).page(params[:page]).per(PER)
      else
        @projects = Project.all.includes([
          :rich_text_content,
          :user,
          location: [:prefecture, :city],
        ]).page(params[:page]).per(PER)
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:title,
                                    :content,
                                    :main_image,
                                    :project_category_id,
                                    :phone_reservation,
                                    location_attributes: [
                                      :prefecture_id,
                                      :id,
                                      :city_id,
                                      :station,
                                    ])
  end

  def correct_project_supplier
    project = Project.find(params[:id])
    redirect_to dashboard_path unless project.user == current_user
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_feed.html.erb
<div class="row">
  <% unless projects.any? %>
    <div class='col-12'>
      募集中のプロジェクトはありません
    </div>
  <% end %>
  <% projects.each do |project| %>
    <div class="col-lg-6 col-md-6 product-box">
      <article class="card card-style2">
        <div class="card-img">
          <%= image_tag project.main_image.index_thumb.url, class: 'rounded-top' %>
          <div class="date"><span><%= project.created_at.strftime("%d") %></span><%= project.created_at.strftime("%b") %></div>
        </div>
        <div class="card-body">
          <% if detail == true %>
            <h2 class="h4"><%= link_to "#{project.title}", detail_project_path(project) %></h3>
          <% else %>
            <h3 class="h5"><%= link_to "#{project.title}", project_path(project) %></h3>
          <% end %>
          <div class="mb-4">
            <span class="small lh-120"> カテゴリー： <%= link_to project.category_name, feed_projects_path(category_id: project.project_category) %> </span><br>
            <span class="small lh-120"><i class="fas fa-map-marker-alt mr-2"></i><%= project.location_name%></span>
          </div>
          <p class="display-30"><%= project.short_content %></p>
        </div>
        <div class="card-footer">
          <ul>
            <%= link_to user_path(project.user) do %>
              <li class='user-name'><i class="fas fa-user"></i><span class='ml-2'><%= project.owner %></span></li>
            <% end %>
            <li class='mr-2'><a href="#!"><i class="far fa-comment-dots"></i><span class='ml-1'>11</span></a></li>
          </ul>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with model: project, local: true, class: 'col-10 mx-auto' do |f| %>
            
  <%= render 'shared/error_messages', resource: project %>

  <div class="form-group">
    <%= f.label :title, 'Title', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>
  </div>

  <div class="form-group">
    <div class='row'>
      <div class='col-12'>
        <%= f.label :project_category_id, 'カテゴリー', class: 'control-label'%>
      </div>
      <div class="col-6">
        <%= f.collection_select :project_category_id, ProjectCategory.all, :id, :name,
                                              { include_blank: "カテゴリを選択してください" }, { class: 'form-control' } %>
      </div>
    </div>
  </div>

  <%= f.fields_for :location do |ff| %>
    <div calss="form-group">
      <div class='row'>
        <div class='col-12'>
          <%= ff.label :prefecture_id, '都道府県', class: 'control-label mt-1'%>
        </div>
        <div class="col-5">
          <%=  ff.collection_select :prefecture_id, Prefecture.all, :id, :name, { include_blank: "---" }, { class: "form-control ChoseTemplate", onchange: "changeTemplate($(this).val())" } %>
        </div>
      </div>
    </div>

    <div calss="form-group">
      <div class='row'>
        <div class='col-12'>
          <%= ff.label :city_id, '市区町村', class: 'control-label mt-4'%>
        </div>
        <div class="col-5 city_select_box">
          <%= ff.collection_select :city_id, [], :id, :name, { include_blank: "---" }, { class: "form-control cities_select_box" } %>
        </div>
      </div>
    </div>

    <div calss="form-group mt-3">
      <div class='row'>
        <div class='col-12'>
          <%= ff.label :station, '最寄り駅', class: 'control-label mt-4'%> <small class='ml-2'>※任意</small>
        </div>
        <div class="col-7">
          <div class="controls">
            <%=  ff.text_field :station, class: 'form-control', placeholder: '〇〇駅' %>
          </div>
        </div>
      </div>
    </div>

  <% end %>

  <div class="form-group mt-4">
    <%= f.label :main_image, 'サムネイル画像', class: 'control-label'%>
    <div class="controls">
      <%= f.file_field :main_image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone_reservation, '電話予約を許可しますか？', class: 'control-label'%>
    <div class="controls">
      <%= f.check_box :phone_reservation %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :content %>
      <%= f.rich_text_area :content %>
    </div>
  </div>

  <p><%= f.submit 'create project', class: 'btn btn-info btn-block' %></p>  
<% end %>


<script>
  function changeTemplate(val){
    var prefecture_id = val;
    $.ajax({
      url: "/prefecture/cities",
      type: "GET",
      data: {
        prefecture_id: prefecture_id
      },
      dataType: "json"
    })
    .done(function(cities){

      $('.cities_select_box > option').remove();
      $('.cities_select_box').append(
          `<option value> --- </option>`
        );
      $(cities).each(function(i, city) {
        $('.cities_select_box').append($("<option>").val(`${city.id}`).text(`${city.name}`));
      });
    })
    console.log(prefecture_id)
  }
</script>

app/views/projects/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <% if current_user %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Reservation!!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <%= link_to new_project_reservation_path(project) do %>
            <button type="button" class="btn btn-primary btn-lg">このまま予約する</button>
          <% end %>
          <% if project.phone_reservation? %>
            <%= link_to new_project_reservation_path(project, reservation_type: 'phone') do %>
              <button type="button" class="btn btn-primary btn-lg">電話で予約する</button>
            <% end %>
          <% else %>
            <button type="button" class="btn btn-secondary btn-lg" style='pointer-events: none;'>このプロジェクトは電話予約できません</button>
          <% end %>
        </div>
      <% else %>

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Reservation!!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <%= link_to new_user_session_path, data: { "turbolinks" => false } do %>
            <button type="button" class="btn btn-primary btn-lg">ログインして予約する</button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/detail.html.erb
<% if current_user %>
  <%= render 'shared/sidenav' %>
<% else %>
  <%= render 'shared/not_sign_in_sidenav' %>
<% end %>

<div class="container">
  <div class="jumbotron">
    <%= render 'shared/notification' %>
    <section id="project-show" class="padding-top-bottom mx-auto">
      <h1 class='text-center'> <%= @project.title%> </h1>
      <div class='col-md-11 mt-5 mx-auto'>
        <p> カテゴリー：<%= link_to @project.category_name, feed_projects_path(category_id: @project.project_category) %> </p>
        <p> project by <%= link_to @project.owner, user_path(@project.user) %></p>
      </div>
      
      <%= image_tag @project.main_image.to_s, class: 'img-fluid d-block mx-auto mt-5' %>
      
      <div class='col-md-9 mt-5 mx-auto'>
        <%= render 'shared/performance_bar', record: @project.performance&.total_record, rate: @project.performance&.average_score %>
        <%= simple_format(h(@project.content)) %>
        <% if current_user != @project.user %>
          <button class="btn btn-info btn-lg mt-5 pull-right" data-toggle="modal" data-target="#exampleModal">reservation now!!</button>
        <% end %>
      </div>

      <%= render 'projects/modal', project: @project %>

    </section>

    <%= render 'comments/index', comments: @comments %>
    <% if current_user && current_user != @project.user %>
      <%= render 'comments/form',  commentable: @project %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">
    <section id="project-form" class="padding-top-bottom">
      <div class="container">
        <div class="row">
          <%= render 'form', project: @project %>
        </div>	
      </div>	
    </section>
  </div>
</div>

app/views/projects/feed.html.erb
<% if current_user %>
  <%= render 'shared/sidenav' %>
<% else %>
  <%= render 'shared/not_sign_in_sidenav' %>
<% end %>

<div class="container">
  <div class="jumbotron">

    <div class="container">
      <% if @prefecture %>
        <h2 class='heading'><span><%= @prefecture.name %>のプロジェクト</span></h2>
      <% else %>
        <div>
          <h3>都道府県</h3>
          <% 1.upto(5) do |n| %>
            <div class='mt-1'>
              <% Prefecture.send("area_#{n}").each do |prefecture| %>
                <%= link_to prefecture.name, feed_projects_path(prefecture: prefecture.name) %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class='mt-5'>
        <%= render 'feed', projects: @projects, detail: true %>
        <div class='pt-5'>
          <%= paginate @projects %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/projects/index.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">

    <%= render 'shared/notification' %>

    <h2 class='heading'><span>My プロジェクト</span></h2>

    <div class="btn-toolbar mb-2 mb-md-0 pt-5 ml-3">
      <%= link_to new_project_path do %>
        <button type="button" class="btn btn-info">new project</button>
      <% end %>
    </div>

    <div class="container pt-5">
      <%= render 'feed', projects: @projects, detail: false %>
      <div class='pt-5'>
        <%= paginate @projects %>
      </div>
    </div>
  </div>

</div>

app/views/projects/new.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">
    <section id="project-form" class="padding-top-bottom">
      <div class="container">
        <div class="row">
          <%= render 'form', project: @project %>
        </div>	
      </div>	
    </section>
  </div>
</div>

app/views/projects/show.html.erb
<%= render 'shared/sidenav' %>

<div class="container">
  <div class="jumbotron">
    <%= render 'shared/notification' %>
    <section id="project-show" class="padding-top-bottom">
      <h1><%= @project.title%> </h1>
      <p> <%= link_to @project.category_name, feed_projects_path(category_id: @project.project_category) %> </p>
      <p> project by <%= link_to @project.owner, user_path(@project.user) %></p>
      <div class='project-image'>
        <%= image_tag @project.main_image.to_s, class: 'img-fluid d-block mx-auto' %>
      </div>

      <div class='project-content mt-5'>
        <%= @project.content %>
      </div>

      <div class='mt-3'>
        <%= link_to edit_project_path(@project) do %>
          <button type="button" class="btn btn-labeled btn-warning">
            edit
          </button>
        <% end %>
        <%= link_to project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <button type="button" class="btn btn-labeled btn-danger">
            delete
          </button>
        <% end %>
      </div>

    </section>
  </div>
</div>